### ISSUE TITLE
Makefile improvements

### ISSUE THREAD

**Issue by HectorPeeters** [29jm/SnowflakeOS#1]
When i was trying to build your project i encountered a few issues on my machine.

- The first time I ran make qemu I got the following error:
`make: ./misc/gen-grub-config.sh: Command not found`
This was quickly solved by changing that line to:
`bash ./misc/gen-grub-config.sh`

- But then the project build succeeded but it did not output a *SnowflakeOS.iso*. After installing `xorriso` it worked perfectly fine! This might be nice to add to the README.md for other people who experience the same problem.

Overall a very nice project!

**Comment by 29jm** [comment]
Thanks for the report and kind words, I'll fix it asap! The whole readme needs some love for sure :)

**Comment by 29jm** [comment]
Done!
