### ISSUE TITLE
calc app is not functional

### ISSUE THREAD

**Issue by 29jm** [29jm/SnowflakeOS#10]
`calc` (source in "modules/src/calc.c") is all UI and no math. Making it work, by using the button callbacks (maybe adding keyboard event support too) and running an expression parser such as the shunting yard algorithm or simpler would be pretty cool!

**Comment by the-grue** [comment]
See #21 as a first pass improvement.

**Comment by 29jm** [comment]
@the-grue Is it cool with you if I @ you in a blog post, regarding this PR?

**Comment by the-grue** [comment]
@29jm  I'd be honored.  Thanks!
