### ISSUE TITLE
Better mouse cursor

### ISSUE THREAD

**Issue by 29jm** [29jm/SnowflakeOS#11]
Currently it's just a grey square, improvement is possible I think ^^

The function in charge of drawing it is [here](https://github.com/29jm/SnowflakeOS/blob/master/kernel/src/misc/wm/wm.c#L437-L446), and note that the pointer is really at the top left corner of its bounding box, i.e. at `(new.left, new.top)` here.

**Comment by the-grue** [comment]
@29jm I'll get this one.  Want to assign it to me?  This will help me get familiar with the gui framework, which is what drew me to this project.

**Comment by 29jm** [comment]
Sure thing, awesome!

**Comment by the-grue** [comment]
Pull request #13 .

**Comment by 29jm** [comment]
Closed by #13 !
