### ISSUE TITLE
Is a debug section possible in README?

### ISSUE THREAD

**Issue by Petross404** [29jm/SnowflakeOS#20]
Do you think you could provide information about how one can debug/ step through the code while it's running on qemu/vbox in the README?

Or provide general technical information about the internals, your implementation etc on your blog so one can keep up and trace the functionality in the actual code. I hope I am being clear and not asking for something vague or annoying from you.

Thanks!

**Comment by 29jm** [comment]
Hi ! I've actually made something like this the other day, it's in the repo's wiki there: 
https://github.com/29jm/SnowflakeOS/wiki/The-edit-debug-cycle
I know this isn't really discoverable, I'll edit the README to mention its existence. Does it answer your questions, could something be added to it?

edit: about technical information for the internals, I was thinking of starting something like that, I'll keep it in mind!

**Comment by Petross404** [comment]
> Does it answer your questions, could something be added to it?

No it's very clear, nice.

> edit: about technical information for the internals, I was thinking of starting something like that, I'll keep it in mind!

I am sure it will be an interesting read.

**Comment by 29jm** [comment]
Closed by a5aa50f56ea9661ff9a77d755eec4e13e1200ce5 and f426ba00fc5905b0c91e28b8edfaef6c78f52cfd!
