### ISSUE TITLE
Loading saves in doom doesn't work

### ISSUE THREAD

**Issue by 29jm** [29jm/SnowflakeOS#22]
Steps to reproduce:
+ checkout the `doom-again` branch
+ compile & run SnowflakeOS
+ run `doom` from the terminal
+ start a new game and make a save
+ restart doom
+ load the save from the main menu: nothing happens, doom outputs
    ```    
    Unknown tclass 122 in savegame
     ```
    and does nothing.

This is indeed a bug in SnowflakeOS because saves work correctly in the linux port, same source.  
Unrelated, but doom is also quite affected by #15.

**Comment by the-grue** [comment]
Hi @29jm !  Just curious, running from a CDROM image, where does the saved file actually go?

**Comment by 29jm** [comment]
Hi @the-grue ! The filesystem is entirely in memory (it's part of the iso and loaded into memory by grub as a module), and the save gets written there through the ext2 driver (`ext2_fs_t::device` is the pointer to the whole filesystem, until it gets replaced by a disk driver). There's currently no way to move data out of the system, it's all volatile. That makes the utility of a savegame discutable yeah ^^ One quick way to get a file out would be to disable printing to serial, and have a function to write a file to serial, but I've never gotten around to it.

**Comment by 29jm** [comment]
Fixed in b2df60fdeae51c878958b2e02f16fdbbf1295eaf.
