### ISSUE TITLE
How do I compile the code it won’t let me install the iso file

### ISSUE THREAD

**Issue by espero-dev** [29jm/SnowflakeOS#40]
Please help me

**Comment by espero-dev** [comment]
<button>

</button>

**Comment by 29jm** [comment]
Hi, the instructions to compile the project are [in the main README](https://github.com/29jm/SnowflakeOS/blob/master/README.md). They expect you to run linux and be proficient at it, Windows is not supported though it could be made to work, in WSL2 for sure.

This OS can't really be "installed" in a way you might expect, the most practical way to run the OS is through QEMU, the procedure is also detailed in the README. You can boot it from a USB drive, but in all likelihood it won't work (as well, at least).

Please open a more detailed issue if you have any more problems.

**Comment by espero-dev** [comment]
Thank you
